"""Implementation of statechart model.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

class Model:
	"""Implementation of the state machine Model.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_robot,
			main_region_robot_mapping_state_bc,
			main_region_robot_movement_control_state_________manual_movement,
			main_region_robot_movement_control_state_________manual_movement_inner_region_forward,
			main_region_robot_movement_control_state_________manual_movement_inner_region_reverse,
			main_region_robot_movement_control_state_________manual_movement_inner_region_a,
			main_region_robot_movement_control_state_________manual_movement_inner_region_d,
			main_region_robot_movement_control_state_________manual_movement_inner_region_stop,
			main_region_robot_movement_control_state_________auto_movement,
			main_region_robot_movement_control_state_________auto_movement_r1base_state,
			main_region_robot_movement_control_state_________auto_movement_r1update_vars,
			main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front,
			main_region_robot_movement_control_state_________auto_movement_r1update_err,
			main_region_robot_movement_control_state_________auto_movement_r1move_forward,
			main_region_robot_movement_control_state_________auto_movement_r1rotate_right,
			main_region_robot_movement_control_state_________auto_movement_r1rotate_left,
			main_region_robot_movement_commands__event_oriented_forward,
			main_region_robot_movement_commands__event_oriented_reverse,
			main_region_robot_movement_commands__event_oriented_rotate_right,
			main_region_robot_movement_commands__event_oriented_stop_moving_forward,
			main_region_robot_movement_commands__event_oriented_stop_reversing,
			main_region_robot_movement_commands__event_oriented_stop_rotating_right,
			main_region_robot_movement_commands__event_oriented_rotate_left,
			main_region_robot_movement_commands__event_oriented_stop_rotating_left,
			main_region_robot_movement_commands__event_oriented_stop,
			null_state
		) = range(26)
	
	
	class UserVar:
		"""Implementation of scope UserVar.
		"""
		
		def __init__(self, statemachine):
			self.base_speed = None
			self.base_rotation = None
			self.startprocedure = None
			self.acceleration_duration = None
			self.rotation_duration = None
			self.min_distance = None
			self.min_front_distance = None
			
			self.statemachine = statemachine
		
	
	class DPID:
		"""Implementation of scope DPID.
		"""
		
		def __init__(self, statemachine):
			self.proportion_gain = None
			self.integral_gain = None
			self.derivation_gain = None
			self.err = None
			self.integral = None
			self.prv_err = None
			self.derivation = None
			self.dpid = None
			self.desired_dist = None
			
			self.statemachine = statemachine
		
	
	class BaseValues:
		"""Implementation of scope BaseValues.
		"""
		
		def __init__(self, statemachine):
			self.max_speed = None
			self.max_rotation = None
			self.degrees_front = None
			self.degrees_right = None
			self.degrees_back = None
			self.degrees_left = None
			
			self.statemachine = statemachine
		
	
	class Output:
		"""Implementation of scope Output.
		"""
		
		def __init__(self, statemachine):
			self.speed = None
			self.rotation = None
			self.obstacles = None
			self.gems = None
			self.finish = None
			
			self.statemachine = statemachine
		
	
	class Grid:
		"""Implementation of scope Grid.
		"""
		
		def __init__(self, statemachine):
			self.update = None
			self.receive = None
			self.column = None
			self.row = None
			self.orientation = None
			self.visited = None
			self.wall_front = None
			self.wall_right = None
			self.wall_back = None
			self.wall_left = None
			self.grid_size = None
			self.max_col = None
			self.max_row = None
			
			self.statemachine = statemachine
		
	
	class StartPos:
		"""Implementation of scope StartPos.
		"""
		
		def __init__(self, statemachine):
			self.set_zero = None
			self.zero_x = None
			self.zero_y = None
			self.zero_south_degree = None
			self.laser_deg_offset = None
			
			self.statemachine = statemachine
		
	
	class Computer:
		"""Implementation of scope Computer.
		"""
		
		def __init__(self, statemachine):
			self.m_press = None
			self.w_press = None
			self.a_press = None
			self.s_press = None
			self.d_press = None
			self.x_press = None
			
			self.statemachine = statemachine
		
		def raise_m_press(self):
			"""Raise method for event m_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_m_press_call)
			self.statemachine.run_cycle()
		
		def __raise_m_press_call(self):
			"""Raise callback for event m_press.
			"""
			self.m_press = True
		
		def raise_w_press(self):
			"""Raise method for event w_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_w_press_call)
			self.statemachine.run_cycle()
		
		def __raise_w_press_call(self):
			"""Raise callback for event w_press.
			"""
			self.w_press = True
		
		def raise_a_press(self):
			"""Raise method for event a_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_a_press_call)
			self.statemachine.run_cycle()
		
		def __raise_a_press_call(self):
			"""Raise callback for event a_press.
			"""
			self.a_press = True
		
		def raise_s_press(self):
			"""Raise method for event s_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_s_press_call)
			self.statemachine.run_cycle()
		
		def __raise_s_press_call(self):
			"""Raise callback for event s_press.
			"""
			self.s_press = True
		
		def raise_d_press(self):
			"""Raise method for event d_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_d_press_call)
			self.statemachine.run_cycle()
		
		def __raise_d_press_call(self):
			"""Raise callback for event d_press.
			"""
			self.d_press = True
		
		def raise_x_press(self):
			"""Raise method for event x_press.
			"""
			self.statemachine.in_event_queue.put(self.__raise_x_press_call)
			self.statemachine.run_cycle()
		
		def __raise_x_press_call(self):
			"""Raise callback for event x_press.
			"""
			self.x_press = True
		
	
	class Imu:
		"""Implementation of scope Imu.
		"""
		
		def __init__(self, statemachine):
			self.pitch = None
			self.roll = None
			self.yaw = None
			
			self.statemachine = statemachine
		
	
	class Odom:
		"""Implementation of scope Odom.
		"""
		
		def __init__(self, statemachine):
			self.x = None
			self.y = None
			self.z = None
			
			self.statemachine = statemachine
		
	
	class LaserDistance:
		"""Implementation of scope LaserDistance.
		"""
		
		def __init__(self, statemachine):
			self.d0 = None
			self.d90 = None
			self.d180 = None
			self.dm90 = None
			self.dmin = None
			self.min_deg = None
			self.dmax = None
			self.max_deg = None
			self.dmean = None
			self.dfront_min = None
			self.min_deg_f = None
			self.dfront_max = None
			self.max_deg_f = None
			self.dfront_mean = None
			self.dright_min = None
			self.min_deg_r = None
			self.dright_max = None
			self.max_deg_r = None
			self.dright_mean = None
			self.dback_min = None
			self.min_deg_b = None
			self.dback_max = None
			self.max_deg_b = None
			self.dback_mean = None
			self.dleft_min = None
			self.min_deg_l = None
			self.dleft_max = None
			self.max_deg_l = None
			self.dleft_mean = None
			
			self.statemachine = statemachine
		
	
	class LaserIntensity:
		"""Implementation of scope LaserIntensity.
		"""
		
		def __init__(self, statemachine):
			self.i0 = None
			self.i90 = None
			self.i180 = None
			self.im90 = None
			self.ifront_min = None
			self.ifront_max = None
			self.ifront_mean = None
			self.iright_min = None
			self.iright_max = None
			self.iright_mean = None
			self.iback_min = None
			self.iback_max = None
			self.iback_mean = None
			self.ileft_min = None
			self.ileft_max = None
			self.ileft_mean = None
			
			self.statemachine = statemachine
		
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		self.user_var = Model.UserVar(self)
		self.dpid = Model.DPID(self)
		self.base_values = Model.BaseValues(self)
		self.output = Model.Output(self)
		self.grid = Model.Grid(self)
		self.start_pos = Model.StartPos(self)
		self.computer = Model.Computer(self)
		self.imu = Model.Imu(self)
		self.odom = Model.Odom(self)
		self.laser_distance = Model.LaserDistance(self)
		self.laser_intensity = Model.LaserIntensity(self)
		
		self.__internal_event_queue = queue.Queue()
		self.in_event_queue = queue.Queue()
		self.stop = None
		self.rotate_right = None
		self.finished_rot_right = None
		self.rotate_left = None
		self.finished_rot_left = None
		self.forward = None
		self.finished_forward = None
		self.reverse = None
		self.finished_reversing = None
		
		# enumeration of all states:
		self.__State = Model.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 3
		for __state_index in range(3):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 4
		
		# initializations:
		#Default init sequence for statechart model
		self.user_var.base_speed = 0.05
		self.user_var.base_rotation = 0.2
		self.user_var.startprocedure = True
		self.user_var.acceleration_duration = 100
		self.user_var.rotation_duration = 80
		self.user_var.min_distance = 0.25
		self.user_var.min_front_distance = 0.5
		self.dpid.proportion_gain = 20.0
		self.dpid.integral_gain = 0.0
		self.dpid.derivation_gain = 5.0
		self.dpid.err = 0.0
		self.dpid.integral = 0.0
		self.dpid.prv_err = 0.0
		self.dpid.derivation = 0.0
		self.dpid.dpid = 0.0
		self.dpid.desired_dist = 0.25
		self.base_values.max_speed = 0.22
		self.base_values.max_rotation = 2.84
		self.base_values.degrees_front = 10
		self.base_values.degrees_right = 10
		self.base_values.degrees_back = 10
		self.base_values.degrees_left = 10
		self.output.speed = 0.0
		self.output.rotation = 0.0
		self.output.obstacles = 0
		self.output.gems = 0
		self.output.finish = 0
		self.grid.update = False
		self.grid.receive = False
		self.grid.column = 0
		self.grid.row = 0
		self.grid.orientation = 0
		self.grid.visited = False
		self.grid.wall_front = 0
		self.grid.wall_right = 0
		self.grid.wall_back = 0
		self.grid.wall_left = 0
		self.grid.grid_size = 0.5
		self.grid.max_col = 3
		self.grid.max_row = 3
		self.start_pos.set_zero = False
		self.start_pos.zero_x = 0.0
		self.start_pos.zero_y = 0.0
		self.start_pos.zero_south_degree = 0.0
		self.start_pos.laser_deg_offset = 0
		self.imu.pitch = 0.0
		self.imu.roll = 0.0
		self.imu.yaw = 0.0
		self.odom.x = 0.0
		self.odom.y = 0.0
		self.odom.z = 0.0
		self.laser_distance.d0 = 0.0
		self.laser_distance.d90 = 0.0
		self.laser_distance.d180 = 0.0
		self.laser_distance.dm90 = 0.0
		self.laser_distance.dmin = 0.0
		self.laser_distance.min_deg = 0
		self.laser_distance.dmax = 0.0
		self.laser_distance.max_deg = 0
		self.laser_distance.dmean = 0.0
		self.laser_distance.dfront_min = 0.0
		self.laser_distance.min_deg_f = 0
		self.laser_distance.dfront_max = 0.0
		self.laser_distance.max_deg_f = 0
		self.laser_distance.dfront_mean = 0.0
		self.laser_distance.dright_min = 0.0
		self.laser_distance.min_deg_r = 0
		self.laser_distance.dright_max = 0.0
		self.laser_distance.max_deg_r = 0
		self.laser_distance.dright_mean = 0.0
		self.laser_distance.dback_min = 0.0
		self.laser_distance.min_deg_b = 0
		self.laser_distance.dback_max = 0.0
		self.laser_distance.max_deg_b = 0
		self.laser_distance.dback_mean = 0.0
		self.laser_distance.dleft_min = 0.0
		self.laser_distance.min_deg_l = 0
		self.laser_distance.dleft_max = 0.0
		self.laser_distance.max_deg_l = 0
		self.laser_distance.dleft_mean = 0.0
		self.laser_intensity.i0 = 0.0
		self.laser_intensity.i90 = 0.0
		self.laser_intensity.i180 = 0.0
		self.laser_intensity.im90 = 0.0
		self.laser_intensity.ifront_min = 0.0
		self.laser_intensity.ifront_max = 0.0
		self.laser_intensity.ifront_mean = 0.0
		self.laser_intensity.iright_min = 0.0
		self.laser_intensity.iright_max = 0.0
		self.laser_intensity.iright_mean = 0.0
		self.laser_intensity.iback_min = 0.0
		self.laser_intensity.iback_max = 0.0
		self.laser_intensity.iback_mean = 0.0
		self.laser_intensity.ileft_min = 0.0
		self.laser_intensity.ileft_max = 0.0
		self.laser_intensity.ileft_mean = 0.0
		self.__completed = False
		self.__do_completion = False
		self.__is_executing = False
		self.__state_conf_vector_position = None
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state or self.__state_vector[2] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_robot:
			return (self.__state_vector[0] >= self.__State.main_region_robot)\
				and (self.__state_vector[0] <= self.__State.main_region_robot_movement_commands__event_oriented_stop)
		if s == self.__State.main_region_robot_mapping_state_bc:
			return self.__state_vector[0] == self.__State.main_region_robot_mapping_state_bc
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement:
			return (self.__state_vector[1] >= self.__State.main_region_robot_movement_control_state_________manual_movement)\
				and (self.__state_vector[1] <= self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop)
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_a:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_a
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_d:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_d
		if s == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement:
			return (self.__state_vector[1] >= self.__State.main_region_robot_movement_control_state_________auto_movement)\
				and (self.__state_vector[1] <= self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left)
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1base_state:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1base_state
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1update_vars:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1update_vars
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1update_err:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1update_err
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1move_forward:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1move_forward
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right
		if s == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left:
			return self.__state_vector[1] == self.__State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left
		if s == self.__State.main_region_robot_movement_commands__event_oriented_forward:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_forward
		if s == self.__State.main_region_robot_movement_commands__event_oriented_reverse:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_reverse
		if s == self.__State.main_region_robot_movement_commands__event_oriented_rotate_right:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_rotate_right
		if s == self.__State.main_region_robot_movement_commands__event_oriented_stop_moving_forward:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_stop_moving_forward
		if s == self.__State.main_region_robot_movement_commands__event_oriented_stop_reversing:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_stop_reversing
		if s == self.__State.main_region_robot_movement_commands__event_oriented_stop_rotating_right:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_stop_rotating_right
		if s == self.__State.main_region_robot_movement_commands__event_oriented_rotate_left:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_rotate_left
		if s == self.__State.main_region_robot_movement_commands__event_oriented_stop_rotating_left:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_stop_rotating_left
		if s == self.__State.main_region_robot_movement_commands__event_oriented_stop:
			return self.__state_vector[2] == self.__State.main_region_robot_movement_commands__event_oriented_stop
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(4):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.__internal_event_queue.empty():
			return self.__internal_event_queue.get()
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_stop(self):
		"""Raise method for event stop.
		"""
		self.__internal_event_queue.put(self.__raise_stop_call)
	
	def __raise_stop_call(self):
		"""Raise callback for event stop.
		"""
		self.stop = True
	
	def raise_rotate_right(self):
		"""Raise method for event rotate_right.
		"""
		self.__internal_event_queue.put(self.__raise_rotate_right_call)
	
	def __raise_rotate_right_call(self):
		"""Raise callback for event rotate_right.
		"""
		self.rotate_right = True
	
	def raise_finished_rot_right(self):
		"""Raise method for event finished_rot_right.
		"""
		self.__internal_event_queue.put(self.__raise_finished_rot_right_call)
	
	def __raise_finished_rot_right_call(self):
		"""Raise callback for event finished_rot_right.
		"""
		self.finished_rot_right = True
	
	def raise_rotate_left(self):
		"""Raise method for event rotate_left.
		"""
		self.__internal_event_queue.put(self.__raise_rotate_left_call)
	
	def __raise_rotate_left_call(self):
		"""Raise callback for event rotate_left.
		"""
		self.rotate_left = True
	
	def raise_finished_rot_left(self):
		"""Raise method for event finished_rot_left.
		"""
		self.__internal_event_queue.put(self.__raise_finished_rot_left_call)
	
	def __raise_finished_rot_left_call(self):
		"""Raise callback for event finished_rot_left.
		"""
		self.finished_rot_left = True
	
	def raise_forward(self):
		"""Raise method for event forward.
		"""
		self.__internal_event_queue.put(self.__raise_forward_call)
	
	def __raise_forward_call(self):
		"""Raise callback for event forward.
		"""
		self.forward = True
	
	def raise_finished_forward(self):
		"""Raise method for event finished_forward.
		"""
		self.__internal_event_queue.put(self.__raise_finished_forward_call)
	
	def __raise_finished_forward_call(self):
		"""Raise callback for event finished_forward.
		"""
		self.finished_forward = True
	
	def raise_reverse(self):
		"""Raise method for event reverse.
		"""
		self.__internal_event_queue.put(self.__raise_reverse_call)
	
	def __raise_reverse_call(self):
		"""Raise callback for event reverse.
		"""
		self.reverse = True
	
	def raise_finished_reversing(self):
		"""Raise method for event finished_reversing.
		"""
		self.__internal_event_queue.put(self.__raise_finished_reversing_call)
	
	def __raise_finished_reversing_call(self):
		"""Raise callback for event finished_reversing.
		"""
		self.finished_reversing = True
	
	def __entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_forward(self):
		"""Entry action for state 'Forward'..
		"""
		#Entry action for state 'Forward'.
		self.raise_forward()
		
	def __entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse(self):
		"""Entry action for state 'Reverse'..
		"""
		#Entry action for state 'Reverse'.
		self.raise_reverse()
		
	def __entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_a(self):
		"""Entry action for state 'A'..
		"""
		#Entry action for state 'A'.
		self.raise_rotate_left()
		
	def __entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_d(self):
		"""Entry action for state 'D'..
		"""
		#Entry action for state 'D'.
		self.raise_rotate_right()
		
	def __entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_stop(self):
		"""Entry action for state 'Stop'..
		"""
		#Entry action for state 'Stop'.
		self.raise_stop()
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_base_state(self):
		""".
		"""
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_update_vars(self):
		""".
		"""
		#Entry action for state 'Update Vars'.
		self.dpid.integral = self.dpid.integral + self.dpid.err
		self.dpid.derivation = (self.dpid.err - self.dpid.prv_err)
		self.dpid.dpid = (((self.dpid.proportion_gain * self.dpid.err) + (self.dpid.integral_gain * self.dpid.integral)) + (self.dpid.derivation_gain * self.dpid.derivation))
		self.dpid.prv_err = self.dpid.err
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front(self):
		"""Entry action for state 'Rotate if wall in front'..
		"""
		#Entry action for state 'Rotate if wall in front'.
		self.raise_rotate_right()
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_update_err(self):
		""".
		"""
		#Entry action for state 'Update Err'.
		self.dpid.err = (self.dpid.desired_dist - self.laser_distance.dleft_mean)
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_move_forward(self):
		"""Entry action for state 'Move Forward'..
		"""
		#Entry action for state 'Move Forward'.
		self.raise_forward()
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right(self):
		"""Entry action for state 'Rotate Right'..
		"""
		#Entry action for state 'Rotate Right'.
		self.raise_rotate_right()
		
	def __entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left(self):
		"""Entry action for state 'Rotate Left'..
		"""
		#Entry action for state 'Rotate Left'.
		self.raise_rotate_left()
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__forward(self):
		"""Entry action for state 'Forward'..
		"""
		#Entry action for state 'Forward'.
		self.timer_service.set_timer(self, 0, self.user_var.acceleration_duration, False)
		self.output.speed = (self.user_var.base_speed * 2)
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__reverse(self):
		"""Entry action for state 'Reverse'..
		"""
		#Entry action for state 'Reverse'.
		self.timer_service.set_timer(self, 1, self.user_var.acceleration_duration, False)
		self.output.speed = (self.user_var.base_speed * -(2))
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__rotate_right(self):
		"""Entry action for state 'Rotate Right'..
		"""
		#Entry action for state 'Rotate Right'.
		self.timer_service.set_timer(self, 2, self.user_var.rotation_duration, False)
		self.output.rotation = (-(self.user_var.base_rotation) * 2)
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__stop_moving_forward(self):
		""".
		"""
		#Entry action for state 'Stop Moving Forward'.
		self.raise_finished_forward()
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__stop_reversing(self):
		""".
		"""
		#Entry action for state 'Stop Reversing'.
		self.raise_finished_reversing()
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__stop_rotating_right(self):
		""".
		"""
		#Entry action for state 'Stop Rotating Right'.
		self.raise_finished_rot_right()
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__rotate_left(self):
		"""Entry action for state 'Rotate Left'..
		"""
		#Entry action for state 'Rotate Left'.
		self.timer_service.set_timer(self, 3, self.user_var.rotation_duration, False)
		self.output.rotation = (self.user_var.base_rotation * 2)
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__stop_rotating_left(self):
		""".
		"""
		#Entry action for state 'Stop Rotating Left'.
		self.raise_finished_rot_left()
		self.__completed = True
		
	def __entry_action_main_region_robot_movement_commands__event_oriented__stop(self):
		"""Entry action for state 'Stop'..
		"""
		#Entry action for state 'Stop'.
		self.output.speed = 0.0
		self.output.rotation = 0.0
		
	def __exit_action_main_region_robot_movement_commands__event_oriented__forward(self):
		"""Exit action for state 'Forward'..
		"""
		#Exit action for state 'Forward'.
		self.timer_service.unset_timer(self, 0)
		
	def __exit_action_main_region_robot_movement_commands__event_oriented__reverse(self):
		"""Exit action for state 'Reverse'..
		"""
		#Exit action for state 'Reverse'.
		self.timer_service.unset_timer(self, 1)
		
	def __exit_action_main_region_robot_movement_commands__event_oriented__rotate_right(self):
		"""Exit action for state 'Rotate Right'..
		"""
		#Exit action for state 'Rotate Right'.
		self.timer_service.unset_timer(self, 2)
		
	def __exit_action_main_region_robot_movement_commands__event_oriented__rotate_left(self):
		"""Exit action for state 'Rotate Left'..
		"""
		#Exit action for state 'Rotate Left'.
		self.timer_service.unset_timer(self, 3)
		
	def __enter_sequence_main_region_robot_default(self):
		"""'default' enter sequence for state Robot.
		"""
		#'default' enter sequence for state Robot
		self.__enter_sequence_main_region_robot_mapping_state_default()
		self.__enter_sequence_main_region_robot_movement_control_state__________default()
		self.__enter_sequence_main_region_robot_movement_commands__event_oriented__default()
		
	def __enter_sequence_main_region_robot_mapping_state_bc_default(self):
		"""'default' enter sequence for state BC.
		"""
		#'default' enter sequence for state BC
		self.__state_vector[0] = self.State.main_region_robot_mapping_state_bc
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_default(self):
		"""'default' enter sequence for state Manual Movement.
		"""
		#'default' enter sequence for state Manual Movement
		self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_default()
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward_default(self):
		"""'default' enter sequence for state Forward.
		"""
		#'default' enter sequence for state Forward
		self.__entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_forward()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_default(self):
		"""'default' enter sequence for state Reverse.
		"""
		#'default' enter sequence for state Reverse
		self.__entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a_default(self):
		"""'default' enter sequence for state A.
		"""
		#'default' enter sequence for state A
		self.__entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_a()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_a
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d_default(self):
		"""'default' enter sequence for state D.
		"""
		#'default' enter sequence for state D
		self.__entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_d()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_d
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop_default(self):
		"""'default' enter sequence for state Stop.
		"""
		#'default' enter sequence for state Stop
		self.__entry_action_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_default(self):
		"""'default' enter sequence for state Auto Movement.
		"""
		#'default' enter sequence for state Auto Movement
		self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_default()
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state_default(self):
		"""'default' enter sequence for state Base State.
		"""
		#'default' enter sequence for state Base State
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_base_state()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1base_state
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_default(self):
		"""'default' enter sequence for state Rotate if wall in front.
		"""
		#'default' enter sequence for state Rotate if wall in front
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err_default(self):
		"""'default' enter sequence for state Update Err.
		"""
		#'default' enter sequence for state Update Err
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_update_err()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1update_err
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward_default(self):
		"""'default' enter sequence for state Move Forward.
		"""
		#'default' enter sequence for state Move Forward
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_move_forward()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1move_forward
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right_default(self):
		"""'default' enter sequence for state Rotate Right.
		"""
		#'default' enter sequence for state Rotate Right
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left_default(self):
		"""'default' enter sequence for state Rotate Left.
		"""
		#'default' enter sequence for state Rotate Left
		self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left()
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__forward_default(self):
		"""'default' enter sequence for state Forward.
		"""
		#'default' enter sequence for state Forward
		self.__entry_action_main_region_robot_movement_commands__event_oriented__forward()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_forward
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__reverse_default(self):
		"""'default' enter sequence for state Reverse.
		"""
		#'default' enter sequence for state Reverse
		self.__entry_action_main_region_robot_movement_commands__event_oriented__reverse()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_reverse
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_right_default(self):
		"""'default' enter sequence for state Rotate Right.
		"""
		#'default' enter sequence for state Rotate Right
		self.__entry_action_main_region_robot_movement_commands__event_oriented__rotate_right()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_rotate_right
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__stop_moving_forward_default(self):
		"""'default' enter sequence for state Stop Moving Forward.
		"""
		#'default' enter sequence for state Stop Moving Forward
		self.__entry_action_main_region_robot_movement_commands__event_oriented__stop_moving_forward()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop_moving_forward
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__stop_reversing_default(self):
		"""'default' enter sequence for state Stop Reversing.
		"""
		#'default' enter sequence for state Stop Reversing
		self.__entry_action_main_region_robot_movement_commands__event_oriented__stop_reversing()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop_reversing
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_right_default(self):
		"""'default' enter sequence for state Stop Rotating Right.
		"""
		#'default' enter sequence for state Stop Rotating Right
		self.__entry_action_main_region_robot_movement_commands__event_oriented__stop_rotating_right()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_right
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_left_default(self):
		"""'default' enter sequence for state Rotate Left.
		"""
		#'default' enter sequence for state Rotate Left
		self.__entry_action_main_region_robot_movement_commands__event_oriented__rotate_left()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_rotate_left
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_left_default(self):
		"""'default' enter sequence for state Stop Rotating Left.
		"""
		#'default' enter sequence for state Stop Rotating Left
		self.__entry_action_main_region_robot_movement_commands__event_oriented__stop_rotating_left()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_left
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__stop_default(self):
		"""'default' enter sequence for state Stop.
		"""
		#'default' enter sequence for state Stop
		self.__entry_action_main_region_robot_movement_commands__event_oriented__stop()
		self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop
		self.__state_conf_vector_position = 2
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __enter_sequence_main_region_robot_mapping_state_default(self):
		"""'default' enter sequence for region Mapping State.
		"""
		#'default' enter sequence for region Mapping State
		self.__react_main_region_robot_mapping_state__entry_default()
		
	def __enter_sequence_main_region_robot_movement_control_state__________default(self):
		"""'default' enter sequence for region Movement Control State         .
		"""
		#'default' enter sequence for region Movement Control State         
		self.__react_main_region_robot_movement_control_state___________entry_default()
		
	def __enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_default(self):
		"""'default' enter sequence for region inner region.
		"""
		#'default' enter sequence for region inner region
		self.__react_main_region_robot_movement_control_state__________manual_movement_inner_region__entry_default()
		
	def __enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_default(self):
		"""'default' enter sequence for region r1.
		"""
		#'default' enter sequence for region r1
		self.__react_main_region_robot_movement_control_state__________auto_movement_r1__entry_default()
		
	def __enter_sequence_main_region_robot_movement_commands__event_oriented__default(self):
		"""'default' enter sequence for region Movement Commands (Event Oriented).
		"""
		#'default' enter sequence for region Movement Commands (Event Oriented)
		self.__react_main_region_robot_movement_commands__event_oriented___entry_default()
		
	def __exit_sequence_main_region_robot_mapping_state_bc(self):
		"""Default exit sequence for state BC.
		"""
		#Default exit sequence for state BC
		self.__state_vector[0] = self.State.main_region_robot
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement(self):
		"""Default exit sequence for state Manual Movement.
		"""
		#Default exit sequence for state Manual Movement
		self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region()
		self.__state_vector[1] = self.State.main_region_robot
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward(self):
		"""Default exit sequence for state Forward.
		"""
		#Default exit sequence for state Forward
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse(self):
		"""Default exit sequence for state Reverse.
		"""
		#Default exit sequence for state Reverse
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a(self):
		"""Default exit sequence for state A.
		"""
		#Default exit sequence for state A
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d(self):
		"""Default exit sequence for state D.
		"""
		#Default exit sequence for state D
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop(self):
		"""Default exit sequence for state Stop.
		"""
		#Default exit sequence for state Stop
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________manual_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement(self):
		"""Default exit sequence for state Auto Movement.
		"""
		#Default exit sequence for state Auto Movement
		self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1()
		self.__state_vector[1] = self.State.main_region_robot
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state(self):
		"""Default exit sequence for state Base State.
		"""
		#Default exit sequence for state Base State
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_vars(self):
		"""Default exit sequence for state Update Vars.
		"""
		#Default exit sequence for state Update Vars
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front(self):
		"""Default exit sequence for state Rotate if wall in front.
		"""
		#Default exit sequence for state Rotate if wall in front
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err(self):
		"""Default exit sequence for state Update Err.
		"""
		#Default exit sequence for state Update Err
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward(self):
		"""Default exit sequence for state Move Forward.
		"""
		#Default exit sequence for state Move Forward
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right(self):
		"""Default exit sequence for state Rotate Right.
		"""
		#Default exit sequence for state Rotate Right
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left(self):
		"""Default exit sequence for state Rotate Left.
		"""
		#Default exit sequence for state Rotate Left
		self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__forward(self):
		"""Default exit sequence for state Forward.
		"""
		#Default exit sequence for state Forward
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		self.__exit_action_main_region_robot_movement_commands__event_oriented__forward()
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__reverse(self):
		"""Default exit sequence for state Reverse.
		"""
		#Default exit sequence for state Reverse
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		self.__exit_action_main_region_robot_movement_commands__event_oriented__reverse()
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_right(self):
		"""Default exit sequence for state Rotate Right.
		"""
		#Default exit sequence for state Rotate Right
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		self.__exit_action_main_region_robot_movement_commands__event_oriented__rotate_right()
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__stop_moving_forward(self):
		"""Default exit sequence for state Stop Moving Forward.
		"""
		#Default exit sequence for state Stop Moving Forward
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__stop_reversing(self):
		"""Default exit sequence for state Stop Reversing.
		"""
		#Default exit sequence for state Stop Reversing
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_right(self):
		"""Default exit sequence for state Stop Rotating Right.
		"""
		#Default exit sequence for state Stop Rotating Right
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_left(self):
		"""Default exit sequence for state Rotate Left.
		"""
		#Default exit sequence for state Rotate Left
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		self.__exit_action_main_region_robot_movement_commands__event_oriented__rotate_left()
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_left(self):
		"""Default exit sequence for state Stop Rotating Left.
		"""
		#Default exit sequence for state Stop Rotating Left
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		
	def __exit_sequence_main_region_robot_movement_commands__event_oriented__stop(self):
		"""Default exit sequence for state Stop.
		"""
		#Default exit sequence for state Stop
		self.__state_vector[2] = self.State.main_region_robot
		self.__state_conf_vector_position = 2
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_robot_mapping_state_bc:
			self.__exit_sequence_main_region_robot_mapping_state_bc()
		state = self.__state_vector[1]
		if state == self.State.main_region_robot_movement_control_state_________manual_movement:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_a:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_d:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1base_state:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_vars:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_vars()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_err:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1move_forward:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left()
		state = self.__state_vector[2]
		if state == self.State.main_region_robot_movement_commands__event_oriented_forward:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__forward()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_reverse:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__reverse()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_rotate_right:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_right()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_moving_forward:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop_moving_forward()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_reversing:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop_reversing()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_right:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_right()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_rotate_left:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_left()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_left:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_left()
		elif state == self.State.main_region_robot_movement_commands__event_oriented_stop:
			self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop()
		
	def __exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region(self):
		"""Default exit sequence for region inner region.
		"""
		#Default exit sequence for region inner region
		state = self.__state_vector[1]
		if state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_a:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_d:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d()
		elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop:
			self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
		
	def __exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1(self):
		"""Default exit sequence for region r1.
		"""
		#Default exit sequence for region r1
		state = self.__state_vector[1]
		if state == self.State.main_region_robot_movement_control_state_________auto_movement_r1base_state:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_vars:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_vars()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_err:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1move_forward:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right()
		elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left:
			self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left()
		
	def __react_main_region_robot_mapping_state__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_mapping_state_bc_default()
		
	def __react_main_region_robot_movement_control_state___________entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
		
	def __react_main_region_robot_movement_control_state__________manual_movement_inner_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop_default()
		
	def __react_main_region_robot_movement_control_state__________auto_movement_r1__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state_default()
		
	def __react_main_region_robot_movement_commands__event_oriented___entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_movement_commands__event_oriented__stop_default()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_robot_default()
		
	def __main_region_robot_react(self, transitioned_before):
		"""Implementation of __main_region_robot_react function.
		"""
		#The reactions of state Robot.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			#Always execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_react function.
		"""
		#The reactions of state Manual Movement.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.computer.m_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_default()
					transitioned_after = 1
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_inner_region_forward_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_inner_region_forward_react function.
		"""
		#The reactions of state Forward.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_forward:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.s_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________manual_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_react function.
		"""
		#The reactions of state Reverse.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_reversing:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.s_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________manual_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_inner_region_a_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_inner_region_a_react function.
		"""
		#The reactions of state A.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_rot_left:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.s_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________manual_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_inner_region_d_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_inner_region_d_react function.
		"""
		#The reactions of state D.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_rot_right:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.s_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________manual_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________manual_movement_inner_region_stop_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________manual_movement_inner_region_stop_react function.
		"""
		#The reactions of state Stop.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.computer.w_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_forward_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.x_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.a_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_a_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
				elif self.computer.d_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_stop()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_inner_region_d_default()
					self.__main_region_robot_movement_control_state__________manual_movement_react(1)
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________manual_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_react function.
		"""
		#The reactions of state Auto Movement.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.computer.m_press or self.computer.s_press:
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement()
					self.__enter_sequence_main_region_robot_movement_control_state__________manual_movement_default()
					transitioned_after = 1
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_base_state_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_base_state_react function.
		"""
		#The reactions of state Base State.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Base State
			self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
			self.__state_conf_vector_position = 1
			#The reactions of state null.
			if self.laser_distance.dfront_mean <= self.user_var.min_front_distance:
				self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_default()
			else:
				self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err_default()
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_update_vars_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_update_vars_react function.
		"""
		#The reactions of state Update Vars.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Update Vars
			self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
			self.__state_conf_vector_position = 1
			#The reactions of state null.
			if self.dpid.dpid > 0.15:
				self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right_default()
			elif self.dpid.dpid < -(0.15):
				self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left_default()
			else:
				self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward_default()
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_react function.
		"""
		#The reactions of state Rotate if wall in front.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if (self.finished_rot_right) and (self.laser_distance.dfront_mean <= self.user_var.min_front_distance):
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_default()
					self.__main_region_robot_movement_control_state__________auto_movement_react(1)
					transitioned_after = 1
				elif (self.finished_rot_right) and (self.laser_distance.dfront_mean > self.user_var.min_front_distance):
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_update_err_default()
					self.__main_region_robot_movement_control_state__________auto_movement_react(1)
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_update_err_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_update_err_react function.
		"""
		#The reactions of state Update Err.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Update Err
			self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement
			self.__state_conf_vector_position = 1
			#'default' enter sequence for state Update Vars
			self.__entry_action_main_region_robot_movement_control_state__________auto_movement_r1_update_vars()
			self.__state_vector[1] = self.State.main_region_robot_movement_control_state_________auto_movement_r1update_vars
			self.__state_conf_vector_position = 1
			self.__state_conf_vector_changed = True
			self.__main_region_robot_movement_control_state__________auto_movement_react(1)
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_move_forward_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_move_forward_react function.
		"""
		#The reactions of state Move Forward.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_forward:
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_base_state_default()
					self.__main_region_robot_movement_control_state__________auto_movement_react(1)
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_rotate_right_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_rotate_right_react function.
		"""
		#The reactions of state Rotate Right.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_rot_right:
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_right()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward_default()
					self.__main_region_robot_movement_control_state__________auto_movement_react(1)
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_control_state__________auto_movement_r1_rotate_left_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_control_state__________auto_movement_r1_rotate_left_react function.
		"""
		#The reactions of state Rotate Left.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 1:
				if self.finished_rot_left:
					self.__exit_sequence_main_region_robot_movement_control_state__________auto_movement_r1_rotate_left()
					self.__enter_sequence_main_region_robot_movement_control_state__________auto_movement_r1_move_forward_default()
					self.__main_region_robot_movement_control_state__________auto_movement_react(1)
					transitioned_after = 1
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_movement_control_state__________auto_movement_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__forward_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__forward_react function.
		"""
		#The reactions of state Forward.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 2:
				if self.__time_events[0] or self.stop:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__forward()
					self.__time_events[0] = False
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__stop_moving_forward_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif (self.forward) and (self.laser_distance.dfront_mean >= self.user_var.min_distance):
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__forward()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__forward_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__reverse_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__reverse_react function.
		"""
		#The reactions of state Reverse.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 2:
				if self.__time_events[1] or self.stop:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__reverse()
					self.__time_events[1] = False
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__stop_reversing_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif self.reverse:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__reverse()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__reverse_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__rotate_right_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__rotate_right_react function.
		"""
		#The reactions of state Rotate Right.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 2:
				if self.__time_events[2] or self.stop:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_right()
					self.__time_events[2] = False
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_right_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif self.rotate_right:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_right()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_right_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__stop_moving_forward_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__stop_moving_forward_react function.
		"""
		#The reactions of state Stop Moving Forward.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Stop Moving Forward
			self.__state_vector[2] = self.State.main_region_robot
			self.__state_conf_vector_position = 2
			#'default' enter sequence for state Stop
			self.__entry_action_main_region_robot_movement_commands__event_oriented__stop()
			self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop
			self.__state_conf_vector_position = 2
			self.__state_conf_vector_changed = True
			self.__main_region_robot_react(0)
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__stop_reversing_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__stop_reversing_react function.
		"""
		#The reactions of state Stop Reversing.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Stop Reversing
			self.__state_vector[2] = self.State.main_region_robot
			self.__state_conf_vector_position = 2
			#'default' enter sequence for state Stop
			self.__entry_action_main_region_robot_movement_commands__event_oriented__stop()
			self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop
			self.__state_conf_vector_position = 2
			self.__state_conf_vector_changed = True
			self.__main_region_robot_react(0)
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__stop_rotating_right_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__stop_rotating_right_react function.
		"""
		#The reactions of state Stop Rotating Right.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Stop Rotating Right
			self.__state_vector[2] = self.State.main_region_robot
			self.__state_conf_vector_position = 2
			#'default' enter sequence for state Stop
			self.__entry_action_main_region_robot_movement_commands__event_oriented__stop()
			self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop
			self.__state_conf_vector_position = 2
			self.__state_conf_vector_changed = True
			self.__main_region_robot_react(0)
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__rotate_left_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__rotate_left_react function.
		"""
		#The reactions of state Rotate Left.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 2:
				if self.__time_events[3] or self.stop:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_left()
					self.__time_events[3] = False
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__stop_rotating_left_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif self.rotate_left:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__rotate_left()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_left_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__stop_rotating_left_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__stop_rotating_left_react function.
		"""
		#The reactions of state Stop Rotating Left.
		transitioned_after = transitioned_before
		if self.__do_completion:
			#Default exit sequence for state Stop Rotating Left
			self.__state_vector[2] = self.State.main_region_robot
			self.__state_conf_vector_position = 2
			#'default' enter sequence for state Stop
			self.__entry_action_main_region_robot_movement_commands__event_oriented__stop()
			self.__state_vector[2] = self.State.main_region_robot_movement_commands__event_oriented_stop
			self.__state_conf_vector_position = 2
			self.__state_conf_vector_changed = True
			self.__main_region_robot_react(0)
		else:
			#Always execute local reactions.
			transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_robot_movement_commands__event_oriented__stop_react(self, transitioned_before):
		"""Implementation of __main_region_robot_movement_commands__event_oriented__stop_react function.
		"""
		#The reactions of state Stop.
		transitioned_after = transitioned_before
		if not self.__do_completion:
			if transitioned_after < 2:
				if self.rotate_left:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_left_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif self.rotate_right:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__rotate_right_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif self.reverse:
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__reverse_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
				elif (self.forward) and (self.laser_distance.dfront_mean >= self.user_var.min_distance):
					self.__exit_sequence_main_region_robot_movement_commands__event_oriented__stop()
					self.__enter_sequence_main_region_robot_movement_commands__event_oriented__forward_default()
					self.__main_region_robot_react(0)
					transitioned_after = 2
			#If no transition was taken
			if transitioned_after == transitioned_before:
				#then execute local reactions.
				transitioned_after = self.__main_region_robot_react(transitioned_before)
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.computer.m_press = False
		self.computer.w_press = False
		self.computer.a_press = False
		self.computer.s_press = False
		self.computer.d_press = False
		self.computer.x_press = False
		self.__time_events[0] = False
		self.__time_events[1] = False
		self.__time_events[2] = False
		self.__time_events[3] = False
	
	
	def __clear_internal_events(self):
		"""Implementation of __clear_internal_events function.
		"""
		self.stop = False
		self.rotate_right = False
		self.finished_rot_right = False
		self.rotate_left = False
		self.finished_rot_left = False
		self.forward = False
		self.finished_forward = False
		self.reverse = False
		self.finished_reversing = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		transitioned = -1
		self.__state_conf_vector_position = 0
		state = self.__state_vector[0]
		if state == self.State.main_region_robot_mapping_state_bc:
			pass
		if self.__state_conf_vector_position < 1:
			state = self.__state_vector[1]
			if state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_forward:
				transitioned = self.__main_region_robot_movement_control_state__________manual_movement_inner_region_forward_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_reverse:
				transitioned = self.__main_region_robot_movement_control_state__________manual_movement_inner_region_reverse_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_a:
				transitioned = self.__main_region_robot_movement_control_state__________manual_movement_inner_region_a_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_d:
				transitioned = self.__main_region_robot_movement_control_state__________manual_movement_inner_region_d_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________manual_movement_inner_region_stop:
				transitioned = self.__main_region_robot_movement_control_state__________manual_movement_inner_region_stop_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1base_state:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_base_state_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_vars:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_update_vars_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_if_wall_in_front:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_rotate_if_wall_in_front_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1update_err:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_update_err_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1move_forward:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_move_forward_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_right:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_rotate_right_react(transitioned)
			elif state == self.State.main_region_robot_movement_control_state_________auto_movement_r1rotate_left:
				transitioned = self.__main_region_robot_movement_control_state__________auto_movement_r1_rotate_left_react(transitioned)
		if self.__state_conf_vector_position < 2:
			state = self.__state_vector[2]
			if state == self.State.main_region_robot_movement_commands__event_oriented_forward:
				self.__main_region_robot_movement_commands__event_oriented__forward_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_reverse:
				self.__main_region_robot_movement_commands__event_oriented__reverse_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_rotate_right:
				self.__main_region_robot_movement_commands__event_oriented__rotate_right_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_moving_forward:
				self.__main_region_robot_movement_commands__event_oriented__stop_moving_forward_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_reversing:
				self.__main_region_robot_movement_commands__event_oriented__stop_reversing_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_right:
				self.__main_region_robot_movement_commands__event_oriented__stop_rotating_right_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_rotate_left:
				self.__main_region_robot_movement_commands__event_oriented__rotate_left_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_stop_rotating_left:
				self.__main_region_robot_movement_commands__event_oriented__stop_rotating_left_react(transitioned)
			elif state == self.State.main_region_robot_movement_commands__event_oriented_stop:
				self.__main_region_robot_movement_commands__event_oriented__stop_react(transitioned)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__do_completion = False
			condition_1 = True
			while condition_1:
				if self.__completed:
					self.__do_completion = True
				self.__completed = False
				self.__micro_step()
				self.__clear_in_events()
				self.__clear_internal_events()
				self.__do_completion = False
				condition_1 = self.__completed
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart model
		self.__enter_sequence_main_region_default()
		self.__do_completion = False
		condition_0 = True
		while condition_0:
			if self.__completed:
				self.__do_completion = True
			self.__completed = False
			self.__micro_step()
			self.__clear_in_events()
			self.__clear_internal_events()
			self.__do_completion = False
			condition_0 = self.__completed
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart model
		self.__exit_sequence_main_region()
		self.__state_vector[0] = self.State.null_state
		self.__state_vector[1] = self.State.null_state
		self.__state_vector[2] = self.State.null_state
		self.__state_conf_vector_position = 2
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
